### ISSUE TITLE
Farben lassen sich nicht mehr ueber das Webinterface speichern!

### ISSUE THREAD

**Issue by DO1JLR** [kr0l/see-base_web#1]
#Fehlermeldung: 
```php
file_put_contents(/var/www/ImpressPages/Theme/see-base_web/assets/style.css): failed to open stream: Permission denied in /var/www/ImpressPages/Ip/Internal/Design/LessCompiler.php:19
```
***Mögliche Ursache:** Commit [00b667ff9620bc66fcd1eb1f3c1c867ce4e2ad31](https://github.com/kr0l/see-base_web/commit/00b667ff9620bc66fcd1eb1f3c1c867ce4e2ad31)*

**Comment by TalviT** [comment]
"Permission denied" hört sich nicht nach einem Problem von dem Template an. Überprüfe mal die Schreibrechte von /var/www.

**Comment by kr0l** [comment]
also ich kann die farben problemlos übers webinterface ändern und speichern

**Comment by DO1JLR** [comment]
# Update:

Der obige Fehlercode ist nach dem Löschen des gesamten Inhalts der Seite und dem neu erstellen verschwunden. Aber ich kann immer noch keine Farben Ändern:

Ich gehe auf `Menu`->`Design` -> `see-base [OPTIONS]` -> Ich ändere eine Farbe -> `Speichern` ->

``` php
Error: file_put_contents(/var/www/ImpressPages/Theme/see-base_web/assets/style.css): failed to open stream: Permission denied in /var/www/ImpressPages/Ip/Internal/Design/LessCompiler.php:196{"result":true,"id":null}
```

Schreibrechte hat das Theme. ich hab mal zum testen alles auf `777`. Aber eigendlich erwarte ich eher, das solche Daten in der MySQL Datenbank gespeichert werden!

**Comment by L3Dokt0r** [comment]
777 auf style.css sollte helfen

**Comment by L3Dokt0r** [comment]
777 auf style.css sollte helfen

**Comment by DO1JLR** [comment]
777 auf style.css sollte helfen
